### ISSUE TITLE
Local build creates broken akeneo-web-api.json

### ISSUE THREAD

**Issue by cplaetzinger** [akeneo/pim-api-docs#304] opened 2019-11-25 14:48 UTC
I cloned the repository for some local testing. Calling `yarn serve` modifies and breakes the file content/swagger/akeneo-web-api.json. I attached a zipped version of the broken file. Any idea what is going wrong here?
[akeneo-web-api.json.gz](https://github.com/akeneo/pim-api-docs/files/3887149/akeneo-web-api.json.gz)

**Comment by LevFlavien** [comment] 2022-05-13 09:51
Not reproduced in current version. Closing this since this is old.

**Closed by LevFlavien** 2022-05-13 09:51 UTC
